### ISSUE TITLE
Python 3 import problem

### ISSUE THREAD

**Issue by ddurieux** [nicolaiarocci/eve-swagger#6]
When import eve-swagger in python3

```
Traceback (most recent call last):
  File "/usr/local/bin/alignak_backend", line 9, in <module>
    load_entry_point('alignak-backend', 'console_scripts', 'alignak_backend')()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Donnees/developpement/sources/Alignak-monitoring/alignak-backend/alignak_backend/main.py", line 6, in <module>
    from alignak_backend.app import app
  File "/Donnees/developpement/sources/Alignak-monitoring/alignak-backend/alignak_backend/app.py", line 31, in <module>
    from eve_swagger import swagger
  File "/usr/local/lib/python3.4/site-packages/eve_swagger/__init__.py", line 10, in <module>
    from swagger import swagger  # noqa
ImportError: No module named 'swagger'
```

**Comment by naoko** [comment]
I've posted PR for this issue: https://github.com/nicolaiarocci/eve-swagger/pull/7

**Comment by nicolaiarocci** [comment]
Just merged it. Thanks!

**Comment by ddurieux** [comment]
Nice, do you think it's possible to make a new release quickly?

**Comment by nicolaiarocci** [comment]
Yes, tomorrow or monday at the latest (hoping to sneak in some new stuff but don't hold your breath)

**Comment by nicolaiarocci** [comment]
v0.0.4 is out

**Comment by ddurieux** [comment]
Thank you very much ;)
